const DEVICES_CONSTS = {
    MM210E: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M210E", type: "module" },
    MM220E: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M220E", type: "module" },
    MM221EINPUT: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M221EINPUT", type: "module" },
    MM221EOUTPUT: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M221EOUTPUT", type: "module" },
    MM201E: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M201E", type: "module" },
    MM501ME: { im: "../../Images/26. M503ME (IRIS).ico", sign: "M501ME", type: "module" },
    MM503ME: { im: "../../Images/26. M503ME (IRIS).ico", sign: "M503ME", type: "module" },
    MM500KAC: { im: "../../Images/26. M503ME (IRIS).ico", sign: "M500KAC", type: "module" },
    MM512ME: { im: "../../Images/29. M512 (IRIS).ico", sign: "M512ME", type: "module" },
    MM201E_240: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M201E_240", type: "module" },
    "MDBS24/EMA24": { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "DBS24/EMA24", type: "module" },
    MIO40: { im: "../../Images/69.SensoIRIS_Module_box.ico", sign: "MIO40", type: "device" },
    MIO04: { im: "../../Images/69.SensoIRIS_Module_box.ico", sign: "MIO04", type: "device" },
    MIO22: { im: "../../Images/69.SensoIRIS_Module_box.ico", sign: "MIO22", type: "device" },
    MIO22M: { im: "../../Images/69.SensoIRIS_Module_box.ico", sign: "MIO22M", type: "device" },
    MINP: { im: "../../Images/1080.MINP.ico", sign: "MINP", type: "device" },
    MINP_FD: { im: "../../Images/1080.MINP.ico", sign: "MINP (FIRE)", type: "device" },
    MINP_GD: { im: "../../Images/1080.MINP.ico", sign: "MINP (GAS)", type: "device" },
    MINP_PANIC: { im: "../../Images/1080.MINP.ico", sign: "MINP (PANIC)", type: "device" },
    MOUT: { im: "../../Images/69.SensoIRIS_Module_box.ico", sign: "MOUT", type: "device" },
    MOUT240_1: { im: "../../Images/69.SensoIRIS_Module_box.ico", sign: "MOUT240_1", type: "device" },
    MOUT240_2: { im: "../../Images/69.SensoIRIS_Module_box.ico", sign: "MOUT240_2", type: "device" },
    ZONEMONITORMC: { im: "../../Images/69.SensoIRIS_Module_box.ico", sign: "ZONEMONITORMC", type: "device" },
    MCP150: { im: "../../Images/1027. Call Point (IRIS).ico", sign: "MCP150", type: "device" },
    T110: { im: "../../Images/70.SensoIRIS_T110_S130.ico", sign: "T110", type: "device" },
    T110_I: { im: "../../Images/70.SensoIRIS_T110_S130.ico", sign: "T110_I", type: "device" },
    S130: { im: "../../Images/70.SensoIRIS_T110_S130.ico", sign: "S130", type: "device" },
    S130_I: { im: "../../Images/70.SensoIRIS_T110_S130.ico", sign: "S130_I", type: "device" },
    M140: { im: "../../Images/71.SensoIRIS_M140.ico", sign: "M140", type: "device" },
    M140_I: { im: "../../Images/71.SensoIRIS_M140.ico", sign: "M140_I", type: "device" },
    WSOU: { im: "../../Images/72.SensoIRIS_WSOU.ico", sign: "WSOU", type: "device" },
    WSOU_I: { im: "../../Images/72.SensoIRIS_WSOU.ico", sign: "WSOU_I", type: "device" },
    WSST: { im: "../../Images/75.SensoIRIS_wsst.ico", sign: "WSST", type: "device" },
    WSST_I: { im: "../../Images/75.SensoIRIS_wsst.ico", sign: "WSST_I", type: "device" },
    WSTR: { im: "../../Images/72.SensoIRIS_WSOU.ico", sign: "WSTR", type: "device" },
    WSTR_I: { im: "../../Images/72.SensoIRIS_WSOU.ico", sign: "WSTR_I", type: "device" },
    BSOU: { im: "../../Images/BSOU-600x460.png", sign: "BSOU", type: "device" },
    BSOU_I: { im: "../../Images/BSOU-600x460.png", sign: "BSOU_I", type: "device" },
    BSST: { im: "../../Images/BSOU-600x460.png", sign: "BSST", type: "device" },
    BSST_I: { im: "../../Images/BSOU-600x460.png", sign: "BSST_I", type: "device" },
    BSTR: { im: "../../Images/BSOU-600x460.png", sign: "BSTR", type: "device" },
    BSTR_I: { im: "../../Images/BSOU-600x460.png", sign: "BSTR_I", type: "device" },
    GAS_DETECTOR: { im: "../../Images/1081.SensoIRIS_GAS.ico", sign: "GAS DETECTOR", type: "device" },
    GAS_DETECTOR_1: { im: "../../Images/1081.SensoIRIS_GAS.ico", sign: "GAS DETECTOR SENSE", type: "device" },
    "ADDR.BASEB24A": { im: "../../Images/68.SensoIRIS_address_base.ico", sign: "ADDR.BASEB24A", type: "device" },
    CALLPOINTMCP50: { im: "../../Images/27. Call Point (IRIS).ico", sign: "CALLPOINT MCP50", type: "device" },
    "INPUT/OUTPUTM22": { im: "../../Images/1058. IRIS M22_IRIS Zone.ico", sign: "INPUT/OUTPUT M22", type: "device" },
    SOUNDERWSOU: { im: "../../Images/1059. Sounder WSOU.ico", sign: "SOUNDER WSOU", type: "device" },
    MIMIC: { im: "../../Images/69.SensoIRIS_Module_box.ico", sign: "MIMIC", type: "device" },
    S1251E: { im: "../../Images/17.1251E.png", sign: "1251E", type: "sensor" },
    S2251EM: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "2251EM", type: "sensor" },
    S2251EIS: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "2251EIS", type: "sensor" },
    S6200: { im: "../../Images/18. 6200 (IRIS).ico", sign: "6200", type: "sensor" },
    SFTXP1: { im: "../../Images/19. Filtrex (IRIS).ico", sign: "FTXP1", type: "sensor" },
    S6500: { im: "../../Images/20. 6500 (IRIS).png", sign: "6500", type: "sensor" },
    S5251EM: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "5251EM", type: "sensor" },
    S5251REM: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "5251REM", type: "sensor" },
    S5251HTEM: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "5251HTEM", type: "sensor" },
    S2251TEM: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "2251TEM", type: "sensor" },
    SLZR1M: { im: "../../Images/17.1251E.png", sign: "LZR1M", type: "sensor" },
    S7251: { im: "../../Images/23. 7251 (IRIS).ico", sign: "7251", type: "sensor" }
};

const BUTTON_IMAGES = {
    TTELOOP: { im: 'fa-solid fa-arrows-spin', sign: 'Teletek Loop' }, // NB! последователността е важна
    LOOP: { im: 'fa-solid fa-arrows-spin', sign: 'System Sensors Loop' },
    OUTREL: { im: 'fa-solid fa-arrow-down-up-across-line', sign: '' },
    OUTMON: { im: 'fa-solid fa-arrow-down-up-across-line', sign: '' },
    POWER: { im: 'fa-solid fa-plug', sign: '' },
    PANELINNETWORK: { im: 'fa-solid fa-display', sign: 'Panel' },
    INPUT: { im: 'fa fa-arrow-down', sign: 'Input' },
    OUTPUT: { im: 'fa fa-arrow-up', sign: 'Output' },
    EVAC_ZONE: { im: 'fa-solid fa-arrows-to-circle', sign: 'EVAC Zone' }, // NB! последователността е важна
    ZONE: { im: 'fa-brands fa-square-font-awesome-stroke', sign: 'Zone' },
};