const DEVICES_CONSTS = {
    IRIS: { im: "imports/images/pics/IRIS.png", sign: "iRIS", type: "panel" },
    IRIS4: { im: "imports/images/pics/iRIS4.png", sign: "iRIS4", type: "panel" },
    IRIS8: { im: "imports/images/pics/iRIS8.png", sign: "iRIS8", type: "panel" },
    REPEATER_TFT: { im: "imports/images/pics/Repeater_TFT.png", sign: "TFT Repeater", type: "panel" },
    TFT_REPEATER: { im: "imports/images/pics/Repeater_TFT.png", sign: "TFT Repeater", type: "panel" },
    REPEATER_IRIS_SIMPO: { im: "imports/images/pics/Repeater.png", sign: "Repeater iRIS/SIMPO", type: "panel" },
    SIMPO: { im: "imports/images/pics/SIMPO.png", sign: "SIMPO", type: "panel" },
    NATRON: { im: "imports/images/pics/NATRON_WE.png", sign: "NATRON", type: "panel" },
    ECLIPSE: { im: "", sign: "Eclipse", type: "panel" },
    ECLIPSE99: { im: "", sign: "Eclipse 99", type: "panel" },
    MM210E: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M210E", type: "module" },
    MM220E: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M220E", type: "module" },
    MM221EINPUT: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M221EINPUT", type: "module" },
    MM221EOUTPUT: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M221EOUTPUT", type: "module" },
    MM201E: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M201E", type: "module" },
    MM501ME: { im: "../../Images/26. M503ME (IRIS).ico", sign: "M501ME", type: "module" },
    MM503ME: { im: "../../Images/26. M503ME (IRIS).ico", sign: "M503ME", type: "module" },
    MM500KAC: { im: "../../Images/26. M503ME (IRIS).ico", sign: "M500KAC", type: "module" },
    MM512ME: { im: "../../Images/29. M512 (IRIS).ico", sign: "M512ME", type: "module" },
    MM201E_240: { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "M201E_240", type: "module" },
    "MDBS24/EMA24": { im: "../../Images/25. M201_M221 (IRIS).ico", sign: "DBS24/EMA24", type: "module" },
    MIO40: { im: "../imports/images/pics/MIO.png", sign: "MIO40", type: "device" },
    MIO04: { im: "../imports/images/pics/MIO.png", sign: "MIO04", type: "device" },
    MIO22: { im: "../imports/images/pics/MIO.png", sign: "MIO22", type: "device" },
    MIO22M: { im: "../imports/images/pics/MIO.png", sign: "MIO22M", type: "device" },
    MINP: { im: "../imports/images/pics/MINP_M.png", sign: "MINP", type: "device" },
    MINP_AK: { im: "../imports/images/pics/MINP_M.png", sign: "MINP AK", type: "device" },
    MINP_FD: { im: "../imports/images/pics/MINP_M.png", sign: "MINP (FIRE)", type: "device" },
    MINP_GD: { im: "../imports/images/pics/MINP_M.png", sign: "MINP (GAS)", type: "device" },
    MINP_PANIC: { im: "../imports/images/pics/MINP_M.png", sign: "MINP (PANIC)", type: "device" },
    MOUT: { im: "../imports/images/pics/MIO.png", sign: "MOUT", type: "device" },
    MOUT240_1: { im: "../imports/images/pics/MIO.png", sign: "MOUT240_1", type: "device" },
    MOUT240_2: { im: "../imports/images/pics/MIO.png", sign: "MOUT240_2", type: "device" },
    ZONEMONITORMC: { im: "../imports/images/pics/MIO.png", sign: "ZONEMONITORMC", type: "device" },
    WL_MCP150: { im: "../imports/images/pics/MCP150.png", sign: "NATRON MCP", type: "device" },
    MCP150: { im: "../imports/images/pics/MCP150.png", sign: "MCP150", type: "device" },
    WL_T110: { im: "../imports/images/pics/NATRON_SD+TD.png", sign: "NATRON TD", type: "device" },
    T110: { im: "../imports/images/pics/S110+S130.png", sign: "T110", type: "device" },
    T110_I: { im: "../imports/images/pics/S110+S130.png", sign: "T110_I", type: "device" },
    WL_S130: { im: "../imports/images/pics/NATRON_SD+TD.png", sign: "NATRON SD", type: "device" },
    S130: { im: "../imports/images/pics/S110+S130.png", sign: "S130", type: "device" },
    S130_I: { im: "../imports/images/pics/S110+S130.png", sign: "S130_I", type: "device" },
    WL_M140: { im: "../imports/images/pics/NATRON_MD.png", sign: "NATRON MD", type: "device" },
    M140: { im: "../imports/images/pics/M140.png", sign: "M140", type: "device" },
    M140_I: { im: "../imports/images/pics/M140.png", sign: "M140_I", type: "device" },
    WSOU: { im: "../imports/images/pics/WSOU.png", sign: "WSOU", type: "device" },
    WSOU_I: { im: "../imports/images/pics/WSOU.png", sign: "WSOU_I", type: "device" },
    WL_WSST: { im: "../imports/images/pics/NATRON_WSS.png", sign: "NATRON WSS", type: "device" },
    WSST: { im: "../imports/images/pics/WSST.png", sign: "WSST", type: "device" },
    WSST_I: { im: "../imports/images/pics/WSST.png", sign: "WSST_I", type: "device" },
    WSTR: { im: "../imports/images/pics/WSOU.png", sign: "WSTR", type: "device" },
    WSTR_I: { im: "../imports/images/pics/WSOU.png", sign: "WSTR_I", type: "device" },
    BSOU: { im: "../imports/images/pics/BSOU.png", sign: "BSOU", type: "device" },
    BSOU_I: { im: "../imports/images/pics/BSOU.png", sign: "BSOU_I", type: "device" },
    BSST: { im: "../imports/images/pics/BSST.png", sign: "BSST", type: "device" },
    BSST_I: { im: "../imports/images/pics/BSST.png", sign: "BSST_I", type: "device" },
    BSTR: { im: "../imports/images/pics/BSOU.png", sign: "BSTR", type: "device" },
    BSTR_I: { im: "../imports/images/pics/BSOU.png", sign: "BSTR_I", type: "device" },
    GAS_DETECTOR: { im: "../imports/images/pics/GAS.png", sign: "GAS DETECTOR", type: "device" },
    GAS_DETECTOR_1: { im: "../imports/images/pics/GAS.png", sign: "GAS DETECTOR SENSE", type: "device" },
    "ADDR.BASEB24A": { im: "../../Images/68.SensoIRIS_address_base.ico", sign: "ADDR.BASEB24A", type: "device" },
    CALLPOINTMCP50: { im: "../../Images/27. Call Point (IRIS).ico", sign: "CALLPOINT MCP50", type: "device" },
    "INPUT/OUTPUTM22": { im: "../../Images/1058. IRIS M22_IRIS Zone.ico", sign: "INPUT/OUTPUT M22", type: "device" },
    SOUNDERWSOU: { im: "../../Images/1059. Sounder WSOU.ico", sign: "SOUNDER WSOU", type: "device" },
    WL_EXPANDER: { im: "../imports/images/pics/NATRON_WE.png", sign: "NATRON WE", type: "device" },
    MIMIC: { im: "../imports/images/pics/MIMIC.png", sign: "MIMIC", type: "device" },
    CSOU: { im: "../imports/images/pics/CSOU.png", sign: "CSOU", type: "device" },
    CSOU_IS: { im: "../imports/images/pics/CSOU+VAD_WST.png", sign: "CSOU_IS", type: "device" },
    CSOU_VAD: { im: "../imports/images/pics/CSOU+VAD_RST.png", sign: "CSOU_VAD", type: "device" },
    CSOU_IS_VAD: { im: "../imports/images/pics/CSOU+VAD_WST.png", sign: "CSOU_IS_VAD", type: "device" },
    CSST: { im: "../imports/images/pics/CSST.png", sign: "CSST", type: "device" },
    CSST_IS: { im: "../imports/images/pics/CSST.png", sign: "CSST_IS", type: "device" },
    MINIOUT: { im: "../imports/images/pics/MiniOUT.png", sign: "MiniOUT", type: "device" },
    default: { im: "", sign: "", type: "device" },
    S1251E: { im: "../../Images/17.1251E.png", sign: "1251E", type: "sensor" },
    S2251EM: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "2251EM", type: "sensor" },
    S2251EIS: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "2251EIS", type: "sensor" },
    S6200: { im: "../../Images/18. 6200 (IRIS).ico", sign: "6200", type: "sensor" },
    SFTXP1: { im: "../../Images/19. Filtrex (IRIS).ico", sign: "FTXP1", type: "sensor" },
    S6500: { im: "../../Images/20. 6500 (IRIS).png", sign: "6500", type: "sensor" },
    S5251EM: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "5251EM", type: "sensor" },
    S5251REM: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "5251REM", type: "sensor" },
    S5251HTEM: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "5251HTEM", type: "sensor" },
    S2251TEM: { im: "../../Images/22. 22051TE (IRIS).ico", sign: "2251TEM", type: "sensor" },
    SLZR1M: { im: "../../Images/17.1251E.png", sign: "LZR1M", type: "sensor" },
    S7251: { im: "../../Images/23. 7251 (IRIS).ico", sign: "7251", type: "sensor" }
};

const BUTTON_IMAGES = {
    TTELOOP: { im: '../imports/images/pics/Teletek_Loop.png', sign: 'Teletek Loop' }, // NB! последователността е важна
    LOOP: { im: '../imports/images/pics/System_Sensor_Loop.png', sign: 'System Sensors Loop' },
    OUTREL: { im: 'fa-solid fa-arrow-down-up-across-line', sign: '' },
    OUTMON: { im: 'fa-solid fa-arrow-down-up-across-line', sign: '' },
    POWER: { im: 'fa-solid fa-plug', sign: '' },
    PANEL: { im: 'panels', sign: 'Panel' },
    INPUT: { im: 'inputs', sign: 'Input' },
    OUTPUT: { im: 'outputs', sign: 'Output' },
    MIMICOUT: { im: 'outputs', sign: 'Output' },
    EVAC_ZONE: { im: 'fa-solid fa-arrows-to-circle', sign: 'EVAC Zone' }, // NB! последователността е важна
    ZONE: { im: 'zones', sign: 'Zone' },
    ORFunction: { im: "../../Images/ORFunction.png", sign: '' },
    ANDFunction: { im: "../../Images/ANDFunction.png", sign: 'Zone' },
    NATRON_MCP: { im: "../imports/images/pics/MCP150.png", sign: "NATRON MCP", type: "device" },
    NATRON_WSS: { im: "../imports/images/pics/NATRON_WSS.png", sign: "NATRON WSS", type: "device" },
    NATRON_TD: { im: "../imports/images/pics/NATRON_SD+TD.png", sign: "NATRON TD", type: "device" },
    NATRON_SD: { im: "../imports/images/pics/NATRON_SD+TD.png", sign: "NATRON SD", type: "device" },
    NATRON_MD: { im: "../imports/images/pics/NATRON_MD.png", sign: "NATRON MD", type: "device" },
    NATRON_NONE: { im: '../imports/images/pics/NATRON_WE.png', sign: 'Natron', type: "device" },
};